on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'Rajat'
    - name: output the memory
      run: |
        echo ${{ steps.hello.outputs.memory }}
        echo "total memory successfully output"
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v2.2.0
      with:
        registry: docker.io
        username: '${{ secrets.DOCKER_USERNAME }}'
        password: '${{ secrets.DOCKER_PASSWORD }}'
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
